# -*- coding: utf-8 -*-
"""LiRA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nuk-Q_Kssz-rNqlMZyeWSp9oTEzaZPX1
"""

# 1. Download resources from HuggingFace
!wget -nc "https://huggingface.co/datasets/SprintML/tml26_task1/resolve/main/pub.pt"
!wget -nc "https://huggingface.co/datasets/SprintML/tml26_task1/resolve/main/priv.pt"
!wget -nc "https://huggingface.co/datasets/SprintML/tml26_task1/resolve/main/model.pt"

# ── CONFIG ────────────────────────────────────────────────────────────────────
N_SHADOWS     = 64     # more = better Gaussian estimates; 64 gives ~32 IN/OUT obs per sample
SHADOW_EPOCHS = 50     # enough to overfit the IN set
BATCH_SIZE    = 128
LR            = 0.01    # SGD + cosine — same procedure as target model
SEED          = 42
# ─────────────────────────────────────────────────────────────────────────────

import sys
import random
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import pandas as pd

from scipy.stats import norm
from torch.utils.data import Dataset, DataLoader, Subset
from torchvision import models
import torchvision.transforms as transforms
from typing import Tuple
from sklearn.metrics import roc_auc_score, roc_curve, balanced_accuracy_score

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

# ─────────────────────────────────────────────────────────────────────────────
# Dataset classes — must exist before torch.load
# ─────────────────────────────────────────────────────────────────────────────
class TaskDataset(Dataset):
    def __init__(self, transform=None):
        self.ids = []; self.imgs = []; self.labels = []
        self.transform = transform

    def __getitem__(self, index) -> Tuple[int, torch.Tensor, int]:
        img = self.imgs[index]
        if self.transform: img = self.transform(img)
        return self.ids[index], img, self.labels[index]

    def __len__(self): return len(self.ids)


class MembershipDataset(TaskDataset):
    def __init__(self, transform=None):
        super().__init__(transform)
        self.membership = []

    def __getitem__(self, index) -> Tuple[int, torch.Tensor, int, int]:
        id_, img, label = super().__getitem__(index)
        return id_, img, label, self.membership[index]


_main = sys.modules["__main__"]
_main.TaskDataset       = TaskDataset
_main.MembershipDataset = MembershipDataset

# ─────────────────────────────────────────────────────────────────────────────
# Normalization — dataset-specific values
# ─────────────────────────────────────────────────────────────────────────────
MEAN = [0.7406, 0.5331, 0.7059]
STD  = [0.1491, 0.1864, 0.1301]

transform = transforms.Compose([
    transforms.Resize((32, 32)),
    transforms.Normalize(mean=MEAN, std=STD),
])

# ─────────────────────────────────────────────────────────────────────────────
# Model factory — identical architecture to target
# ─────────────────────────────────────────────────────────────────────────────
def build_resnet18(num_classes=9):
    m = models.resnet18(weights=None)
    m.conv1   = nn.Conv2d(3, 64, kernel_size=3, stride=1, padding=1, bias=False)
    m.maxpool = nn.Identity()
    m.fc      = nn.Linear(m.fc.in_features, num_classes)
    return m

# ─────────────────────────────────────────────────────────────────────────────
# Logit transform  φ(p) = log(p / (1-p))
# Maps confidence ∈ (0,1) → (-∞, +∞) for Gaussian fitting
# ─────────────────────────────────────────────────────────────────────────────
def logit(p: np.ndarray) -> np.ndarray:
    p = np.clip(p, 1e-7, 1 - 1e-7)
    return np.log(p / (1 - p))

# ─────────────────────────────────────────────────────────────────────────────
# Extract confidence on TRUE label from a model over a loader
# Returns: {sample_id: confidence_float}
# ─────────────────────────────────────────────────────────────────────────────
@torch.no_grad()
def get_true_label_conf(model, loader, device):
    """
    For every sample, returns the model's softmax probability assigned
    to the TRUE label (not the predicted label).
    This is the signal LiRA uses — members should have higher
    true-label confidence because the model was trained to predict them.
    """
    model.eval()
    id_to_conf = {}

    for batch in loader:
        ids      = batch[0]
        imgs     = batch[1].to(device)
        labels_b = batch[2].to(device).long()

        probs      = F.softmax(model(imgs), dim=1)           # (B, 9)
        true_confs = probs.gather(                           # (B, 1)
            1, labels_b.view(-1, 1)
        ).squeeze(1).cpu().numpy()                           # (B,)

        for id_, conf in zip(ids.tolist(), true_confs.tolist()):
            id_to_conf[int(id_)] = float(conf)

    return id_to_conf

# ─────────────────────────────────────────────────────────────────────────────
# Shadow model training
# ─────────────────────────────────────────────────────────────────────────────
def train_shadow(in_indices, pub_ds, epochs, device):
    """
    Train one shadow ResNet on `in_indices` (members only).
    Same optimizer / schedule as the target model.
    in_indices: list of pub_ds indices this shadow trains on.
    """
    loader    = DataLoader(Subset(pub_ds, in_indices),
                           batch_size=BATCH_SIZE, shuffle=True,
                           num_workers=2, pin_memory=True)
    model     = build_resnet18().to(device)
    optimizer = torch.optim.SGD(model.parameters(), lr=LR,
                                momentum=0.9, weight_decay=5e-4)
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)
    criterion = nn.CrossEntropyLoss()

    model.train()
    for epoch in range(1, epochs + 1):
        for _, imgs, labels, _ in loader:
            imgs, labels = imgs.to(device), labels.to(device).long()
            optimizer.zero_grad()
            criterion(model(imgs), labels).backward()
            optimizer.step()
        scheduler.step()
        if epoch % 10 == 0:
            print(f"      epoch {epoch}/{epochs}", flush=True)

    model.eval()
    return model

# ─────────────────────────────────────────────────────────────────────────────
# Evaluation
# ─────────────────────────────────────────────────────────────────────────────
def evaluate(scores_dict, pub_ds, label=""):
    """
    Compute TPR@5%FPR and AUC on pub.pt using ground truth membership labels.
    scores_dict: {sample_id: lira_score}
    Membership labels are ONLY used here for evaluation — never during training.
    """
    ids = sorted(scores_dict.keys())
    sc  = np.array([scores_dict[i] for i in ids])

    id_to_mem = {int(pub_ds.ids[i]): int(pub_ds.membership[i])
                 for i in range(len(pub_ds))}
    gt = np.array([id_to_mem[i] for i in ids])

    auc = roc_auc_score(gt, sc)
    fprs_, tprs_, thresholds_ = roc_curve(gt, sc)
    tpr_5fpr = float(tprs_[fprs_ <= 0.05][-1]) if (fprs_ <= 0.05).any() else 0.0

    # Optimal balanced accuracy threshold
    bal_accs = np.array([
        balanced_accuracy_score(gt, (sc >= t).astype(int))
        for t in thresholds_
    ])
    best_t   = thresholds_[np.argmax(bal_accs)]
    best_bal = bal_accs.max()

    tag = f"[{label}] " if label else ""
    print(f"  {tag}AUC          : {auc:.4f}")
    print(f"  {tag}TPR@5%FPR   : {tpr_5fpr:.4f}  ← leaderboard metric")
    print(f"  {tag}Balanced Acc : {best_bal:.4f}  (threshold={best_t:.3f})")
    return tpr_5fpr

# ── Load pub.pt ───────────────────────────────────────────────────────────────
print("Loading pub.pt ...")
data   = torch.load("pub.pt", weights_only=False)
pub_ds = MembershipDataset(transform=transform)
pub_ds.ids        = data.ids
pub_ds.imgs       = data.imgs
pub_ds.labels     = data.labels
pub_ds.membership = data.membership

N_PUB          = len(pub_ds)
pub_sample_ids = [int(pub_ds.ids[i]) for i in range(N_PUB)]   # ordered list of IDs
id_to_pubidx   = {id_: i for i, id_ in enumerate(pub_sample_ids)}

# Separate member and non-member indices
member_idx    = [i for i in range(N_PUB) if pub_ds.membership[i] == 1]
nonmember_idx = [i for i in range(N_PUB) if pub_ds.membership[i] == 0]

print(f"  Total: {N_PUB} | Members: {len(member_idx)} | "
      f"Non-members: {len(nonmember_idx)}")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"  Device: {device}")

# ── Load target model ─────────────────────────────────────────────────────────
print("\nLoading target model ...")
target_model = build_resnet18()
target_model.load_state_dict(torch.load("model.pt", map_location=device))
target_model = target_model.to(device)
target_model.eval()

# ── Full pub loader (shuffle=False — order must stay fixed) ───────────────────
pub_loader = DataLoader(pub_ds, batch_size=BATCH_SIZE, shuffle=False,
                        num_workers=2, pin_memory=True)

# ─────────────────────────────────────────────────────────────────────────────
# STEP 1: Get target model's true-label confidence on pub.pt
# This is φ_target(x) — plugged into the Gaussians at scoring time.
# Computed once here, never recomputed.
# ─────────────────────────────────────────────────────────────────────────────
print("\nStep 1: Computing target model confidence on pub.pt ...")
target_conf_pub = get_true_label_conf(target_model, pub_loader, device)
# target_conf_pub: {id: confidence}  — true-label softmax prob from target

# ─────────────────────────────────────────────────────────────────────────────
# STEP 2: Train N shadow models, collect IN/OUT logit-confidences per sample
#
# in_confs[i]  = list of logit(conf) values from shadows that trained on sample i
# out_confs[i] = list of logit(conf) values from shadows that did NOT train on sample i
#
# Key facts:
#   - Shadows only train on members (mirroring the target)
#   - Each shadow uses a different random 50% of members as its IN set
#   - Non-members are always OUT for every shadow
#   - IN/OUT labels are determined per-shadow by the random split — completely
#     independent of the ground truth membership labels in pub.pt
# ─────────────────────────────────────────────────────────────────────────────
print(f"\nStep 2: Training {N_SHADOWS} shadow models ...")

in_confs  = [[] for _ in range(N_PUB)]   # indexed by pub_ds position
out_confs = [[] for _ in range(N_PUB)]   # indexed by pub_ds position

for k in range(N_SHADOWS):
    print(f"\n  Shadow {k+1}/{N_SHADOWS}", flush=True)

    # Random 50/50 split of members for this shadow
    perm        = member_idx.copy()
    random.shuffle(perm)
    half        = len(perm) // 2
    in_idx      = perm[:half]          # pub_ds indices this shadow trains on
    in_id_set   = {pub_sample_ids[i] for i in in_idx}   # IDs → for fast lookup

    print(f"    IN members: {len(in_idx)} | OUT members: {half} | "
          f"OUT non-members: {len(nonmember_idx)}")

    # Train shadow on IN members only
    shadow = train_shadow(in_idx, pub_ds, SHADOW_EPOCHS, device)

    # Collect true-label confidence from this shadow over ALL pub samples
    shadow_conf = get_true_label_conf(shadow, pub_loader, device)
    # shadow_conf: {id: confidence}

    # Route each sample's confidence to in_confs or out_confs
    # based on whether THIS shadow trained on it — NOT ground truth membership
    for pub_pos, sample_id in enumerate(pub_sample_ids):
        phi = logit(np.array([shadow_conf[sample_id]]))[0]   # scalar logit-conf

        if sample_id in in_id_set:
            # This shadow was trained on sample_id → IN observation
            in_confs[pub_pos].append(phi)
        else:
            # This shadow was NOT trained on sample_id → OUT observation
            # Covers: OUT members (other 50%) + all non-members
            out_confs[pub_pos].append(phi)

    del shadow
    if torch.cuda.is_available():
        torch.cuda.empty_cache()

    # Progress: show how many observations each sample has so far
    if (k + 1) % 8 == 0:
        avg_in  = np.mean([len(c) for c in in_confs])
        avg_out = np.mean([len(c) for c in out_confs])
        print(f"    Avg IN obs/sample: {avg_in:.1f} | "
              f"Avg OUT obs/sample: {avg_out:.1f}")

print("\nIN/OUT observation counts after all shadows:")
in_counts  = [len(c) for c in in_confs]
out_counts = [len(c) for c in out_confs]
print(f"  IN  — mean: {np.mean(in_counts):.1f} | "
      f"min: {np.min(in_counts)} | max: {np.max(in_counts)}")
print(f"  OUT — mean: {np.mean(out_counts):.1f} | "
      f"min: {np.min(out_counts)} | max: {np.max(out_counts)}")

sample_mu_in  = np.mean([np.mean(c) for c in in_confs  if len(c) > 0])
sample_mu_out = np.mean([np.mean(c) for c in out_confs if len(c) > 0])
print(f"Mean μ_in across samples:  {sample_mu_in:.4f}")
print(f"Mean μ_out across samples: {sample_mu_out:.4f}")
print(f"μ_in > μ_out: {sample_mu_in > sample_mu_out}  (True = standard direction)")
# If False → use log_p_out - log_p_in

# ─────────────────────────────────────────────────────────────────────────────
# STEP 3: Fit per-sample Gaussians and compute LiRA scores for pub.pt
#
# For each sample x:
#   μ_in,  σ_in  = mean/std of in_confs[x]   (logit-space)
#   μ_out, σ_out = mean/std of out_confs[x]  (logit-space)
#   φ_target     = logit(target_conf_pub[x])
#   score(x)     = log N(φ_target | μ_in, σ_in)
#                - log N(φ_target | μ_out, σ_out)
# ─────────────────────────────────────────────────────────────────────────────
print("\nStep 3: Computing LiRA scores for pub.pt ...")

pub_scores = {}

for pub_pos, sample_id in enumerate(pub_sample_ids):
    ic = np.array(in_confs[pub_pos])
    oc = np.array(out_confs[pub_pos])

    # Fit Gaussians — need at least 2 observations for std
    mu_in  = ic.mean() if len(ic) >= 1 else 0.0
    std_in = ic.std()  if len(ic) >= 2 else 1.0
    std_in = max(std_in, 1e-8)   # prevent division by zero

    mu_out  = oc.mean() if len(oc) >= 1 else 0.0
    std_out = oc.std()  if len(oc) >= 2 else 1.0
    std_out = max(std_out, 1e-8)

    # Target model's logit-confidence on this sample
    phi_target = logit(np.array([target_conf_pub[sample_id]]))[0]

    # Log likelihood ratio
    log_p_in  = norm.logpdf(phi_target, loc=mu_in,  scale=std_in)
    log_p_out = norm.logpdf(phi_target, loc=mu_out, scale=std_out)
    pub_scores[sample_id] = float(log_p_out - log_p_in)

# ─────────────────────────────────────────────────────────────────────────────
# STEP 4: Evaluate on pub.pt
# Ground truth membership labels used HERE ONLY — never during shadow training
# ─────────────────────────────────────────────────────────────────────────────
print("\nStep 4: Evaluating on pub.pt ...")
evaluate(pub_scores, pub_ds, label="pub LiRA")

# ─────────────────────────────────────────────────────────────────────────────
# STEP 5: Score priv.pt
#
# priv.pt samples were never part of any shadow's training — we cannot build
# per-sample Gaussians for them. Instead we use GLOBAL distributions:
#   μ_in_global, σ_in_global   = pooled over all in_confs from pub.pt
#   μ_out_global, σ_out_global = pooled over all out_confs from pub.pt
#
# These represent "what IN/OUT looks like in general for this architecture
# and dataset" — the best available proxy for unseen samples.
# ─────────────────────────────────────────────────────────────────────────────
print("\nStep 5: Computing global Gaussians for priv.pt ...")

all_in_logits  = np.concatenate([np.array(c) for c in in_confs  if len(c) > 0])
all_out_logits = np.concatenate([np.array(c) for c in out_confs if len(c) > 0])

mu_in_g  = all_in_logits.mean();  std_in_g  = max(all_in_logits.std(),  1e-8)
mu_out_g = all_out_logits.mean(); std_out_g = max(all_out_logits.std(), 1e-8)

print(f"  Global IN  distribution: μ={mu_in_g:.4f}, σ={std_in_g:.4f}")
print(f"  Global OUT distribution: μ={mu_out_g:.4f}, σ={std_out_g:.4f}")
print(f"  μ_in - μ_out = {mu_in_g - mu_out_g:.4f}  "
      f"(positive = members have higher confidence, as expected)")

# Load priv.pt
print("\nLoading priv.pt and extracting target model confidence ...")
priv_raw = torch.load("priv.pt", weights_only=False)

class PrivateDataset(Dataset):
    def __init__(self, ids, imgs, labels, transform=None):
        self.ids = ids; self.imgs = imgs
        self.labels = labels; self.transform = transform
    def __getitem__(self, i):
        img = self.imgs[i]
        if self.transform: img = self.transform(img)
        return self.ids[i], img, self.labels[i]
    def __len__(self): return len(self.ids)

priv_ds = PrivateDataset(
    ids=priv_raw.ids, imgs=priv_raw.imgs,
    labels=priv_raw.labels, transform=transform
)
priv_loader = DataLoader(priv_ds, batch_size=BATCH_SIZE, shuffle=False,
                         num_workers=2, pin_memory=True)

# Get target model's true-label confidence on priv.pt
target_conf_priv = get_true_label_conf(target_model, priv_loader, device)

# Score each priv sample using global Gaussians
priv_scores = {}
for sample_id, conf in target_conf_priv.items():
    phi = logit(np.array([conf]))[0]
    log_p_in  = norm.logpdf(phi, loc=mu_in_g,  scale=std_in_g)
    log_p_out = norm.logpdf(phi, loc=mu_out_g, scale=std_out_g)
    priv_scores[sample_id] = float(log_p_out - log_p_in)

# ─────────────────────────────────────────────────────────────────────────────
# STEP 6: Write submission.csv
# ─────────────────────────────────────────────────────────────────────────────
print("\nStep 6: Writing submission.csv ...")

# Normalize scores to [0, 1] — required by submission format
all_vals = np.array(list(priv_scores.values()))
vmin, vmax = all_vals.min(), all_vals.max()
normalized = {id_: float((s - vmin) / (vmax - vmin))
              for id_, s in priv_scores.items()}

submission = pd.DataFrame({
    "id":    list(normalized.keys()),
    "score": list(normalized.values())
})

# Sanity checks
assert len(submission) == 14000,                   "Wrong number of rows"
assert list(submission.columns) == ["id", "score"],"Wrong columns"
assert submission["id"].is_unique,                  "Duplicate IDs"
assert submission["score"].between(0, 1).all(),     "Scores out of [0,1]"
assert not submission["score"].isna().any(),         "NaN scores"

submission.to_csv("submission.csv", index=False)
print(f"  Saved submission.csv — {len(submission)} rows")
print(submission["score"].describe().round(4))

